name: Update List

on: 
  schedule:
    - cron:  '16 8 * * 1,3,5'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
          path: main

      - name: Refresh
        run: main/script/run.sh 

      - name: Save Repo
        uses: EndBug/add-and-commit@v9
        with:
          cwd: main
