name: Update List

on: 
  push:
    branches:
      - master
  schedule:
    - cron:  '16 8 * * 1,3,5'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CERT_REPO }}
          path: main

      - name: Refresh
        run: main/script/run.sh 

      - name: Save Repo
        uses: EndBug/add-and-commit@v9
        with:
          cwd: main
